class SportsEvent {
  final String iconUrl;
  final String league;
  final String teams;
  final String sportType;
  final String dateStarting;
  final String timeStarting;

  SportsEvent({
    required this.iconUrl,
    required this.league,
    required this.teams,
    required this.sportType,
    required this.dateStarting,
    required this.timeStarting,
  });

  factory SportsEvent.fromMap(Map<String, dynamic> map) {
    return SportsEvent(
      iconUrl: map['iconUrl'] as String,
      league: map['league'] as String,
      teams: map['teams'] as String,
      sportType: map['sportType'] as String,
      dateStarting: map['dateStarting'] as String,
      timeStarting: map['timeStarting'] as String,
    );
  }
}

final List<SportsEvent> sportsEvents = [
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/2158/2158416.png',
    league: 'Lega B',
    teams: 'Juventus vs. Roma',
    sportType: 'Basketball',
    dateStarting: 'Yesterday',
    timeStarting: '16:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/2158/2158416.png',
    league: 'Serie A',
    teams: 'Juventus vs. Inter Milan',
    sportType: 'Football',
    dateStarting: 'Yesterday',
    timeStarting: '16:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/919/919836.png',
    league: 'Premier League',
    teams: 'Manchester United vs. Liverpool',
    sportType: 'Football',
    dateStarting: 'Yesterday',
    timeStarting: '19:30',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/919/919831.png',
    league: 'La Liga',
    teams: 'Real Madrid vs. Barcelona',
    sportType: 'Football',
    dateStarting: 'Yesterday',
    timeStarting: '21:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/327/327779.png',
    league: 'NBA',
    teams: 'Lakers vs. Celtics',
    sportType: 'Basketball',
    dateStarting: 'Yesterday',
    timeStarting: '18:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/327/327785.png',
    league: 'EuroLeague',
    teams: 'Real Madrid vs. CSKA Moscow',
    sportType: 'Basketball',
    dateStarting: 'Yesterday',
    timeStarting: '20:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/1041/1041917.png',
    league: 'ATP',
    teams: 'Djokovic vs. Thiem',
    sportType: 'Tennis',
    dateStarting: 'Yesterday',
    timeStarting: '14:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/1041/1041917.png',
    league: 'WTA',
    teams: 'Serena vs. Williams',
    sportType: 'Tennis',
    dateStarting: 'Yesterday',
    timeStarting: '16:30',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/2158/2158416.png',
    league: 'Serie A',
    teams: 'Milan vs. Munich',
    sportType: 'Football',
    dateStarting: 'Today',
    timeStarting: '14:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/2158/2158416.png',
    league: 'Bundesliga',
    teams: 'Bayern Munich vs. Borussia Dortmund',
    sportType: 'Football',
    dateStarting: 'Today',
    timeStarting: '14:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/919/919836.png',
    league: 'MLS',
    teams: 'LA Galaxy vs. Seattle Sounders',
    sportType: 'Football',
    dateStarting: 'Today',
    timeStarting: '16:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/919/919831.png',
    league: 'Ligue 1',
    teams: 'Paris Saint-Germain vs. Lyon',
    sportType: 'Football',
    dateStarting: 'Today',
    timeStarting: '19:45',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/327/327779.png',
    league: 'NBA',
    teams: 'Heat vs. Bucks',
    sportType: 'Basketball',
    dateStarting: 'Today',
    timeStarting: '19:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/327/327785.png',
    league: 'EuroLeague',
    teams: 'Fenerbahçe vs. Zalgiris Kaunas',
    sportType: 'Basketball',
    dateStarting: 'Today',
    timeStarting: '21:30',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/1041/1041917.png',
    league: 'ATP',
    teams: 'Medvedev vs. Alcaraz',
    sportType: 'Tennis',
    dateStarting: 'Today',
    timeStarting: '13:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/1041/1041917.png',
    league: 'WTA',
    teams: 'Barty vs. Osaka',
    sportType: 'Tennis',
    dateStarting: 'Today',
    timeStarting: '15:30',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/1037/1037507.png',
    league: 'MLB',
    teams: 'Yankees vs. Red Sox',
    sportType: 'Baseball',
    dateStarting: 'Today',
    timeStarting: '18:15',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/1037/1037507.png',
    league: 'Nippon Professional Baseball',
    teams: 'Yomiuri Giants vs. Hanshin Tigers',
    sportType: 'Baseball',
    dateStarting: 'Today',
    timeStarting: '20:45',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/2158/2158416.png',
    league: 'Eredivisie',
    teams: 'Ajax vs. PSV Eindhoven',
    sportType: 'Football',
    dateStarting: 'Tomorrow',
    timeStarting: '15:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/919/919836.png',
    league: 'Primeira Liga',
    teams: 'Porto vs. Benfica',
    sportType: 'Football',
    dateStarting: 'Tomorrow',
    timeStarting: '17:30',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/919/919831.png',
    league: 'Major League Soccer',
    teams: 'Toronto FC vs. New York City FC',
    sportType: 'Football',
    dateStarting: 'Tomorrow',
    timeStarting: '20:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/327/327779.png',
    league: 'NBA',
    teams: 'Knicks vs. Nets',
    sportType: 'Basketball',
    dateStarting: 'Tomorrow',
    timeStarting: '19:30',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/327/327785.png',
    league: 'EuroLeague',
    teams: 'CSKA Moscow vs. Olimpia Milano',
    sportType: 'Basketball',
    dateStarting: 'Tomorrow',
    timeStarting: '21:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/1041/1041917.png',
    league: 'ATP',
    teams: 'Tsitsipas vs. Zverev',
    sportType: 'Tennis',
    dateStarting: 'Tomorrow',
    timeStarting: '14:30',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/1041/1041917.png',
    league: 'WTA',
    teams: 'Swiatek vs. Svitolina',
    sportType: 'Tennis',
    dateStarting: 'Tomorrow',
    timeStarting: '16:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/1037/1037507.png',
    league: 'MLB',
    teams: 'Dodgers vs. Giants',
    sportType: 'Baseball',
    dateStarting: 'Tomorrow',
    timeStarting: '19:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/1037/1037507.png',
    league: 'KBO League',
    teams: 'Doosan Bears vs. Kia Tigers',
    sportType: 'Baseball',
    dateStarting: 'Tomorrow',
    timeStarting: '21:30',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/2945/2945013.png',
    league: 'NHL',
    teams: 'Maple Leafs vs. Bruins',
    sportType: 'Hockey',
    dateStarting: 'Today',
    timeStarting: '20:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/2945/2945013.png',
    league: 'KHL',
    teams: 'SKA Saint Petersburg vs. CSKA Moscow',
    sportType: 'Hockey',
    dateStarting: 'Tomorrow',
    timeStarting: '22:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/2965/2965567.png',
    league: 'NFL',
    teams: 'Patriots vs. Dolphins',
    sportType: 'American Football',
    dateStarting: 'Today',
    timeStarting: '17:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/2965/2965567.png',
    league: 'CFL',
    teams: 'Toronto Argonauts vs. Montreal Alouettes',
    sportType: 'Canadian Football',
    dateStarting: 'Tomorrow',
    timeStarting: '19:30',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/2889/2889598.png',
    league: 'UFC',
    teams: 'Conor McGregor vs. Dustin Poirier',
    sportType: 'MMA',
    dateStarting: 'Yesterday',
    timeStarting: '22:00',
  ),
  SportsEvent(
    iconUrl: 'https://cdn-icons-png.flaticon.com/512/2889/2889598.png',
    league: 'Bellator',
    teams: 'Daniel Cormier vs. Ryan Bader',
    sportType: 'MMA',
    dateStarting: 'Tomorrow',
    timeStarting: '20:30',
  ),
];
